### ISSUE TITLE
Support logo configuration

### ISSUE THREAD

**Issue by jncraton** [jncraton/inferential#65]
As an administrator, I can use the config file to specify a logo URL (either stored in the static folder or as an external URL) to customize the webpage. The logo should be used for the favicon and in the header of both the playground and status page.
- [x] Add default icon to config file
- [x] Add image to header of playground (#68)
- [x] Add image to header of status page (#68)
- [x] Change image based on config file
- [x] Change favicon based on config file (#69)
